/* ============================================================
   ALPHA WOOLLENS — PRODUCT CATALOG DATA
   ------------------------------------------------------------
   This is the single source of truth for every catalog item.
   To add a product: copy an object below and edit the fields.
   To add a category: add an entry to CATEGORIES and start using
   its `id` as a product's `category`.
   ============================================================ */

const CATEGORIES = [
  { id: "security",     label: "Security Apparel",      icon: "shield" },
  { id: "school",       label: "School Uniforms",       icon: "school" },
  { id: "knitwear",     label: "Sweaters & Knitwear",   icon: "sweater" },
  { id: "protective",   label: "Protective Workwear",   icon: "vest" },
  { id: "corporate",    label: "Corporate Wear",        icon: "shirt" },
  { id: "headwear",     label: "Headwear",              icon: "cap" },
  { id: "accessories",  label: "Equipment & Accessories", icon: "belt" },
  { id: "branding",     label: "Branding & Customization", icon: "stitch" },
];

const PRODUCTS = [
  // ---------------- SECURITY APPAREL ----------------
  {
    id: "sec-uniform-navy-red",
    name: "Security Uniform — Navy & Red Trim",
    category: "security",
    img: "assets/images/products/security-uniform-front.jpg",
    gallery: ["assets/images/products/security-uniform-front.jpg","assets/images/products/security-uniform-back.jpg","assets/images/products/security-uniform-flatlay.jpg"],
    short: "Short-sleeve shirt and cargo trouser set with signature red piping.",
    description: "Our flagship security uniform pairs a reinforced-pocket shirt with red accent piping and matching cargo trousers, built for all-day patrol wear. Comes with optional rank epaulettes and embroidered insignia.",
    features: ["Short & long sleeve shirt options", "Reinforced cargo trousers", "Custom insignia & embroidery", "Available in navy, black, grey"],
  },
  {
    id: "sec-uniform-sweater-combo",
    name: "Security Uniform — Sweater Combo",
    category: "security",
    img: "assets/images/products/security-uniform-sweater-combo.jpg",
    gallery: ["assets/images/products/security-uniform-sweater-combo.jpg"],
    short: "Cold-weather patrol set combining ribbed sweater with trouser uniform.",
    description: "A layered uniform option for cold-weather shifts — ribbed knit sweater with shoulder reinforcement worn over the standard uniform shirt, paired with matching trousers.",
    features: ["Ribbed knit construction", "Reinforced shoulder patches", "Pairs with standard uniform trousers"],
  },
  {
    id: "sec-uniform-navy-plain",
    name: "Security Uniform — Classic Navy",
    category: "security",
    img: "assets/images/products/security-uniform-navy-plain.jpg",
    gallery: ["assets/images/products/security-uniform-navy-plain.jpg"],
    short: "Understated navy uniform for corporate security teams.",
    description: "A cleaner, understated uniform silhouette for corporate and front-of-house security roles, finished with cargo trousers and ready for custom badge placement.",
    features: ["Plain navy finish", "Custom badge placement", "Cargo trouser fit"],
  },
  {
    id: "sec-uniform-grey-canon",
    name: "Security Uniform — Long Sleeve Charcoal",
    category: "security",
    img: "assets/images/products/security-uniform-grey-canon.jpg",
    gallery: ["assets/images/products/security-uniform-grey-canon.jpg"],
    short: "Long-sleeve charcoal shirt with cap and branded trousers.",
    description: "Long-sleeve charcoal uniform shirt with matching navy trousers, finished with custom security-company branding and cap. Suited to firms wanting a darker, low-profile uniform.",
    features: ["Long sleeve charcoal shirt", "Matching cap included", "Full custom branding on trousers"],
  },
  {
    id: "sec-sweaters",
    name: "Security Sweaters",
    category: "security",
    img: "assets/images/products/security-sweaters-trio.jpg",
    gallery: ["assets/images/products/security-sweaters-trio.jpg"],
    short: "Lightweight, soft & warm ribbed sweaters in black, navy, or green.",
    description: "Crew-neck and V-neck sweaters with ribbed cuffs, hem and collar. Lightweight yet warm, designed for layering over the standard uniform shirt during colder shifts.",
    features: ["Crew-neck or V-neck", "Ribbed cuffs, hem & collar", "Black, Navy, Green — mix & match", "Shoulder reinforcement patches"],
  },
  {
    id: "raincoat",
    name: "Security Raincoat",
    category: "security",
    img: "assets/images/products/raincoat-model-front-back.jpg",
    gallery: ["assets/images/products/raincoat-flat.jpg","assets/images/products/raincoat-model-front-back.jpg"],
    short: "Full-length hooded raincoat with custom back branding.",
    description: "A full-length hooded raincoat built for outdoor security posts in wet conditions, with custom company name printed across the back for visibility and identification.",
    features: ["Full-length hooded design", "Custom back & chest branding", "Snap-button closure", "Lightweight waterproof shell"],
  },

  // ---------------- SCHOOL UNIFORMS ----------------
  {
    id: "school-boys",
    name: "Boys' School Uniform Suite",
    category: "school",
    img: "assets/images/products/cap-with-swatches.jpg",
    gallery: [],
    short: "Shirts, trousers, ties, sweaters and sportswear for boys.",
    description: "A complete uniform suite for boys covering daily wear and sports: shirts & t-shirts, trousers & shorts, school ties & belts, premium knit sweaters, sports t-shirts & shorts, and socks.",
    features: ["Shirts & T-Shirts", "Trousers & Shorts", "School Ties & Belts", "Premium Knit Sweaters", "Sports T-Shirts and Shorts", "Socks"],
    placeholder: true,
  },
  {
    id: "school-girls",
    name: "Girls' School Uniform Suite",
    category: "school",
    img: "assets/images/products/cardigan-black.jpg",
    gallery: [],
    short: "Blouses, skirts/pinafores, sweaters and sportswear for girls.",
    description: "A complete uniform suite for girls covering daily wear and sports: blouses, shirts & t-shirts, skirts & pinafores, school ties & belts, premium knit sweaters, sports t-shirts & shorts, and socks.",
    features: ["Blouses, Shirts & T-Shirts", "Skirts & Pinafores", "School Ties & Belts", "Premium Knit Sweaters", "Sports T-Shirts and Shorts", "Socks"],
    placeholder: true,
  },

  // ---------------- KNITWEAR ----------------
  {
    id: "vneck-sweaters",
    name: "V-Neck Sweaters",
    category: "knitwear",
    img: "assets/images/products/vneck-sweaters-collection.jpg",
    gallery: ["assets/images/products/vneck-sweaters-collection.jpg"],
    short: "School, corporate and security V-neck sweaters with custom embroidery.",
    description: "Long-sleeve V-neck sweaters available in school, corporate, and security uniform variants. Custom logo embroidery available on request.",
    features: ["School / Corporate / Security variants", "Custom logo embroidery", "Available in multiple colourways"],
  },
  {
    id: "cardigans",
    name: "Button-Up Cardigans",
    category: "knitwear",
    img: "assets/images/products/cardigan-black.jpg",
    gallery: ["assets/images/products/cardigan-black.jpg"],
    short: "School and corporate cardigans with full button front.",
    description: "Classic button-up cardigans suited to school and corporate uniform programmes, offering a smart layering option over shirts and blouses.",
    features: ["Full button-up front", "School & corporate fit options", "Soft knit construction"],
  },
  {
    id: "sleeveless-sweaters",
    name: "Sleeveless Sweaters & Jerseys",
    category: "knitwear",
    img: "assets/images/products/sleeveless-sweaters.jpg",
    gallery: ["assets/images/products/sleeveless-sweaters.jpg"],
    short: "Army, police & security jerseys in sleeveless V-neck cut.",
    description: "Sleeveless V-neck jerseys designed for army, police, and security applications — a breathable layering piece worn over a uniform shirt.",
    features: ["Sleeveless V-neck cut", "Army & Police jersey styles", "Security jersey variant"],
  },
  {
    id: "highneck-sweater",
    name: "High-Neck Sweater",
    category: "knitwear",
    img: "assets/images/products/highneck-sweater.jpg",
    gallery: ["assets/images/products/highneck-sweater.jpg"],
    short: "Turtleneck-style sweater for cold-weather corporate or security wear.",
    description: "A fitted high-neck (turtleneck) sweater offering extra warmth and coverage, suited to colder climates or night-shift security roles.",
    features: ["High / turtle neck design", "Fitted ribbed construction", "Available in navy and dark tones"],
  },
  {
    id: "beanie-hats",
    name: "Beanie Hats",
    category: "knitwear",
    img: "assets/images/products/beanie-hats-stack.jpg",
    gallery: ["assets/images/products/beanie-hats-stack.jpg","assets/images/products/beanie-color-swatches.jpg"],
    short: "Knit beanies in black, navy, olive and grey.",
    description: "Warm knit beanie hats available in four core colours, suitable for security, industrial, and outdoor staff during cold conditions.",
    features: ["Black, Navy, Olive, Grey", "Ribbed knit cuff", "One-size stretch fit"],
  },
  {
    id: "balaclava",
    name: "Balaclava Caps",
    category: "knitwear",
    img: "assets/images/products/balaclava-cap.jpg",
    gallery: ["assets/images/products/balaclava-cap.jpg"],
    short: "Full-face knit balaclava for cold-weather security duty.",
    description: "Knit balaclava cap offering full head and neck coverage for security and outdoor industrial staff working in cold or windy conditions.",
    features: ["Full head & neck coverage", "Soft knit construction", "One-size fit"],
  },
  {
    id: "hand-gloves",
    name: "Hand Gloves",
    category: "knitwear",
    img: "assets/images/products/hand-gloves.jpg",
    gallery: ["assets/images/products/hand-gloves.jpg"],
    short: "Knit hand gloves for cold-weather outdoor duty.",
    description: "Durable knit gloves for security and outdoor industrial staff, offering warmth without compromising grip and dexterity.",
    features: ["Knit construction", "Navy colourway", "Suited to outdoor & night shifts"],
  },

  // ---------------- PROTECTIVE WORKWEAR ----------------
  {
    id: "overalls",
    name: "Industrial Overalls",
    category: "protective",
    img: "assets/images/products/overalls-color-range.jpg",
    gallery: ["assets/images/products/overalls-color-range.jpg"],
    short: "Durable coveralls in grey, navy, khaki, orange, red and blue.",
    description: "Heavy-duty industrial overalls built for rigorous environments, available across six core colourways. Customisation available upon request.",
    features: ["Grey, Navy, Khaki, Orange, Red, Blue", "Reinforced pockets", "Customisation available upon request"],
  },
  {
    id: "overall-hivis",
    name: "Reflective Hi-Vis Overall",
    category: "protective",
    img: "assets/images/products/overall-hivis-navy.jpg",
    gallery: ["assets/images/products/overall-hivis-navy.jpg"],
    short: "Navy coverall with reflective hi-vis striping for low-light safety.",
    description: "A navy industrial coverall fitted with reflective hi-vis striping across the arms and legs, designed for staff working in low-light or high-traffic industrial environments.",
    features: ["Reflective hi-vis striping", "Navy base with yellow reflective tape", "Full-body coverage"],
  },
  {
    id: "dust-lab-coats",
    name: "Dust Coats & Lab Coats",
    category: "protective",
    img: "assets/images/products/dust-coats-collection.jpg",
    gallery: ["assets/images/products/dust-coats-collection.jpg"],
    short: "Professional overcoats for laboratories and dusty facility environments.",
    description: "Lightweight dust coats and laboratory coats designed to protect everyday clothing in facility and laboratory environments. Available in white, navy, charcoal and blue.",
    features: ["Laboratory & facility use", "White, Navy, Charcoal, Blue", "Lightweight breathable fabric"],
  },
  {
    id: "facility-uniform",
    name: "Facility Shirt & Trouser Set",
    category: "protective",
    img: "assets/images/products/facility-shirts.jpg",
    gallery: ["assets/images/products/facility-shirts.jpg","assets/images/products/facility-trousers.jpg"],
    short: "Short-sleeve facility shirts and matching cargo trousers.",
    description: "A practical shirt and cargo-trouser uniform set for facility, maintenance and industrial staff, available in green, khaki, navy and teal.",
    features: ["Short sleeve shirt", "Matching cargo trousers", "Green, Khaki, Navy, Teal"],
  },
  {
    id: "aprons-full",
    name: "Full-Length Aprons",
    category: "protective",
    img: "assets/images/products/aprons-full-length.jpg",
    gallery: ["assets/images/products/aprons-full-length.jpg"],
    short: "Full-length aprons with ties, zips and pockets.",
    description: "Full-length bib aprons with adjustable ties and front pockets, suited to industrial, hospitality and laboratory environments. Available in black, blue, pinstripe and green.",
    features: ["Adjustable neck tie", "Front pockets", "Black, Blue, Pinstripe, Green"],
  },
  {
    id: "aprons-short",
    name: "Short Waist Aprons",
    category: "protective",
    img: "assets/images/products/apron-short-black.jpg",
    gallery: ["assets/images/products/apron-short-black.jpg","assets/images/products/apron-short-white.jpg"],
    short: "Half-length waist aprons in black pinstripe and white.",
    description: "Half-length waist aprons with front pocket, designed for hospitality and light industrial use. Available in black pinstripe and plain white.",
    features: ["Waist-tie closure", "Front pocket", "Black pinstripe or white"],
  },

  // ---------------- CORPORATE WEAR ----------------
  {
    id: "corporate-shirts-light",
    name: "Corporate Shirts — Light Tones",
    category: "corporate",
    img: "assets/images/products/corporate-shirts-light.jpg",
    gallery: ["assets/images/products/corporate-shirts-light.jpg"],
    short: "Tailored corporate shirts in light lilac, ready for brand embroidery.",
    description: "Tailored corporate shirts with a clean modern collar, available in light tones and ready for custom brand embroidery on the chest.",
    features: ["Tailored modern collar", "Custom embroidery placement", "Men's and women's cuts"],
  },
  {
    id: "corporate-shirts-blue",
    name: "Corporate Shirts — Blue",
    category: "corporate",
    img: "assets/images/products/corporate-shirts-blue.jpg",
    gallery: ["assets/images/products/corporate-shirts-blue.jpg"],
    short: "Two-tone blue corporate shirts with white piping detail.",
    description: "Smart two-tone blue corporate shirts finished with contrast white piping, designed for front-of-house and corporate teams. Custom embroidery available.",
    features: ["Two-tone colour blocking", "Contrast piping detail", "Custom embroidery & branding"],
  },
  {
    id: "tshirts-roundneck",
    name: "Round-Neck T-Shirts",
    category: "corporate",
    img: "assets/images/products/tshirts-roundneck.jpg",
    gallery: ["assets/images/products/tshirts-roundneck.jpg"],
    short: "Round-neck branded t-shirts in five core colours.",
    description: "Classic round-neck t-shirts available in yellow, white, black, navy and green, ready for your brand print or embroidery.",
    features: ["Round neck cut", "5 core colours", "Custom brand printing"],
  },
  {
    id: "tshirts-longsleeve",
    name: "Long-Sleeve T-Shirts",
    category: "corporate",
    img: "assets/images/products/tshirts-longsleeve.jpg",
    gallery: ["assets/images/products/tshirts-longsleeve.jpg"],
    short: "Long-sleeve branded t-shirts for cooler conditions.",
    description: "Long-sleeve t-shirts offering extra coverage for cooler conditions or sun protection, available in five core colours with custom branding.",
    features: ["Long sleeve cut", "5 core colours", "Custom brand printing"],
  },
  {
    id: "polos-collar",
    name: "Collared Polo Shirts",
    category: "corporate",
    img: "assets/images/products/polos-collar.jpg",
    gallery: ["assets/images/products/polos-collar.jpg","assets/images/products/polos-collection2.jpg"],
    short: "Branded polo shirts with collar, in six core colours.",
    description: "Smart-casual polo shirts with structured collar, ideal for corporate and retail teams. Available in white, blue, navy, red and yellow, with custom chest embroidery.",
    features: ["Structured collar", "6 core colours", "Custom chest embroidery"],
  },

  // ---------------- HEADWEAR ----------------
  {
    id: "branded-caps",
    name: "Branded Caps",
    category: "headwear",
    img: "assets/images/products/cap-with-swatches.jpg",
    gallery: ["assets/images/products/cap-with-swatches.jpg"],
    short: "Structured baseball caps in 8 colours with custom embroidery.",
    description: "Structured six-panel baseball caps available in eight core colours, with custom brand embroidery across the front panel.",
    features: ["6-panel structured fit", "8 core colours", "Front panel embroidery"],
  },
  {
    id: "safari-hats",
    name: "Safari Hats",
    category: "headwear",
    img: "assets/images/products/safari-hat.jpg",
    gallery: ["assets/images/products/safari-hat.jpg"],
    short: "Wide-brim safari hats with adjustable chin strap.",
    description: "Wide-brim safari-style hats offering sun protection for outdoor staff, with an adjustable chin strap and custom embroidery option.",
    features: ["Wide brim sun protection", "Adjustable chin strap", "Custom embroidery"],
  },
  {
    id: "bucket-hats",
    name: "Bucket Hats",
    category: "headwear",
    img: "assets/images/products/bucket-hats.jpg",
    gallery: ["assets/images/products/bucket-hats.jpg"],
    short: "Branded bucket hats in black and khaki.",
    description: "Casual bucket hats suited to outdoor events and promotional wear, available in black and khaki with custom brand embroidery.",
    features: ["Black & khaki colourways", "Custom embroidery", "Casual outdoor fit"],
  },
  {
    id: "berets",
    name: "Berets",
    category: "headwear",
    img: "assets/images/products/beret.jpg",
    gallery: ["assets/images/products/beret.jpg"],
    short: "Wool beret with leather trim for formal security/ceremonial wear.",
    description: "Traditional wool beret with leather edge trim, used for ceremonial and formal security dress uniforms.",
    features: ["Wool construction", "Leather edge trim", "Ceremonial / dress uniform use"],
  },
  {
    id: "security-caps",
    name: "Security Caps",
    category: "headwear",
    img: "assets/images/products/security-cap.jpg",
    gallery: ["assets/images/products/security-cap.jpg"],
    short: "Structured peaked cap for daily security uniform wear.",
    description: "A structured peaked cap designed as standard daily headwear for security personnel, available with custom insignia.",
    features: ["Structured peak design", "Custom insignia badge", "Navy standard colourway"],
  },

  // ---------------- EQUIPMENT & ACCESSORIES ----------------
  {
    id: "baton-pr24",
    name: "Baton (PR24) & Holder",
    category: "accessories",
    img: "assets/images/products/baton-holder-pr24.jpg",
    gallery: ["assets/images/products/baton-holder-pr24.jpg"],
    short: "Standard-issue PR24 security baton with belt holder.",
    description: "Standard-issue PR24 security baton paired with a webbing belt holder, a core equipment item for security personnel.",
    features: ["PR24 standard baton", "Webbing belt holder", "Quick-release ring"],
  },
  {
    id: "security-belts",
    name: "Security Belts",
    category: "accessories",
    img: "assets/images/products/security-belts.jpg",
    gallery: ["assets/images/products/security-belts.jpg"],
    short: "Reinforced webbing duty belts in multiple colourways.",
    description: "Heavy-duty webbing belts used to carry equipment such as batons and radios, available in a range of colourways to match uniform branding.",
    features: ["Reinforced webbing", "Multiple colourways", "Equipment attachment loops"],
  },
  {
    id: "whistles",
    name: "Security Whistles",
    category: "accessories",
    img: "assets/images/products/security-whistle.jpg",
    gallery: ["assets/images/products/security-whistle.jpg"],
    short: "Metal duty whistle with keyring attachment.",
    description: "A classic metal duty whistle with keyring attachment, standard equipment for security and patrol staff.",
    features: ["Polished metal finish", "Keyring attachment", "High-audibility design"],
  },
  {
    id: "socks",
    name: "Uniform Socks",
    category: "accessories",
    img: "assets/images/products/socks.jpg",
    gallery: ["assets/images/products/socks.jpg"],
    short: "Crew socks in tan, olive and navy.",
    description: "Comfortable crew-length socks designed to pair with school and security uniform footwear, available in tan, olive and navy.",
    features: ["Crew length", "Tan, Olive, Navy", "Reinforced heel & toe"],
  },

  // ---------------- BRANDING & CUSTOMIZATION ----------------
  {
    id: "embroidery",
    name: "Embroidery Services",
    category: "branding",
    img: "assets/images/products/corporate-shirts-blue.jpg",
    gallery: [],
    short: "Precision embroidery for logos, badges and insignia.",
    description: "Precision embroidery services for corporate logos, school badges, and official security insignia — built to hold up to repeated industrial washing.",
    features: ["Corporate logos & school badges", "Official security insignia", "Personalised name tags"],
    placeholder: true,
  },
  {
    id: "screen-printing",
    name: "Screen Printing",
    category: "branding",
    img: "assets/images/products/tshirts-roundneck.jpg",
    gallery: ["assets/images/products/tshirts-roundneck.jpg"],
    short: "Durable screen printing for bold, large-format branding.",
    description: "Durable screen printing suited to bold, large-format branding across t-shirts, polos and outerwear.",
    features: ["Large-format brand prints", "Durable industrial-wash finish", "Multi-colour printing available"],
  },
  {
    id: "heat-transfer",
    name: "Heat Transfer Printing",
    category: "branding",
    img: "assets/images/products/polos-collar.jpg",
    gallery: ["assets/images/products/polos-collar.jpg"],
    short: "Precision heat-transfer printing for fine detail branding.",
    description: "Precision heat-transfer printing for fine-detail branding where embroidery or screen printing isn't suitable.",
    features: ["Fine detail reproduction", "Photographic-quality logos", "Fast turnaround"],
  },
];

// Helper used by catalog.html
function getCategoryLabel(id) {
  const c = CATEGORIES.find((c) => c.id === id);
  return c ? c.label : id;
}
